version: "3.8"

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-service
    ports:
      - "8000:8000"
    network_mode: host
  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    network_mode: host

volumes:
  data:
